### ISSUE TITLE
Clipped point symbols at high zoom levels

### ISSUE THREAD

**Issue by gregbacchus** [perliedman/ocad2geojson#22]
See image example. When zoomed in point symbols are clipped (I assume to show only on the tile that they are centred in)

![image](https://github.com/perliedman/ocad2geojson/assets/1761608/add493d0-0ea2-4ffb-b7ab-b8d33f77cd2c)

**Comment by perliedman** [comment]
Hi!

Is this using the mapbox GL styling, or where do you see this?

I think you're right that this is an issue with how the tiles are clipped. Ideally, there would be overlap in each tile so the features render on both sides of the tile seam.

**Comment by gregbacchus** [comment]
Hi,
Sorry, I should have specified. I noticed it here: https://o-scout.vercel.app/

**Comment by perliedman** [comment]
Alright, thanks! So this is most likely an issue with [ocad-tiler](https://github.com/perliedman/ocad-tiler) which does not buffer the tiles. I see I _have_ added a `buffer` option in it, but it does not look like it's working as expected. I will open a bug there and close this one!
