### ISSUE TITLE
Run client-side?

### ISSUE THREAD

**Issue by jankoc** [perliedman/ocad2geojson#27]
I tried to get this to run client-side by building via browserify, but didn't get it to work (but tbh I don't have much experience with that). Should that be possible? I'd want to convert an OCAD course-file to geojson to further manipulate it in a client-side website.

**Comment by perliedman** [comment]
Hi, yes it should definitely be possible. My main use case for this lib is running it in the browser.

You can see examples of it running here: https://o-scout.vercel.app/ (source: https://github.com/perliedman/o-scout/)
There's also a more basic, but probably outdated, example in library's own codebase: https://github.com/perliedman/ocad2geojson/blob/master/examples/viewer/index.js
