### ISSUE TITLE
Curves are not supported (yet?) when rendering to SVG/PDF?

### ISSUE THREAD

**Issue by mpickering** [perliedman/ocad2geojson#4]
For example:

![image](https://user-images.githubusercontent.com/1216657/78452384-e94a2d00-7682-11ea-9e81-42b92c512df9.png)
vs 

![image](https://user-images.githubusercontent.com/1216657/78452391-f2d39500-7682-11ea-8dfa-45e742e68ab6.png)

**Comment by mpickering** [comment]
Seems to me that the SVG exporter does not distinguish between the different point types at all so the lines also join up all the bezier anchors.

The way to fix this is to mirror what happens in the geojson exporter where the coordinates are traversed and the bezier anchors matched with the other control points. After that, SVG already has native support for drawing quadratic bezier curves.

**Comment by perliedman** [comment]
Fixed by #6, right?
